name: Fetch Courses

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

#      - name: Install Pandoc
#        run: |
#          sudo apt-get install pandoc

      - name: List dir
        run: |
          cd ../..
          pwd
          ls

#      - name: npm install
#        run: |
#          npm install

      - name: Fetch Course Data
        run: |
          node app.js

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
